Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/admin2/TechCare_project/techcare_env/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'soporte.ana-hn.org:437'. You may need to add 'soporte.ana-hn.org' to ALLOWED_HOSTS.
